author:
  # Biographic information
  avatar           : "/images/Junyi.jpeg"
  name             : "Junyi Li"
  bio              : "PhD Candidate in Information Systems, National University of Singapore"
  location         : "Singapore"
  employer         : "National University of Singapore"
  email            : "junyili [at] u [dot] nus [dot] edu"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=mqeGEBgAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0002-5415-6209"

  # Repositories
  github           : "GrandJune"

  # Social media
  linkedin         : "junyi-li-018409105"
